version: '3'
services:
  bot:
    build:
      context: .
      args:
        NODE_ENV: development
        DB_CONNECTION_STRING: mongodb://localhost:27018/botman
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./sounds:/app/sounds
      - ./logs:/app/logs
    entrypoint: ["yarn", "run", "start:dev"]
    ports:
      - 8000:80
  db:
    image: mongo:4
    volumes:
      - db:/data/db
    ports:
      - 27018:27017

volumes:
  db:
    driver: local
