import React, { FC } from 'react';

const LogoutPointer: FC = () => (
  // eslint-disable-next-line max-len
  <img className="log-out-pointer" src="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABcAAAAICAMAAAAldJTcAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAPFBMVEXBuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP3BuP0AAABV8EQTAAAAEnRSTlMAWMhXHaemHOLhY+7thf3x8IRfavZpAAAAAWJLR0QTDLtclgAAAAlwSFlzAAASdAAAEnQB3mYfeAAAAAd0SU1FB+YIHRUPHvmw1osAAABCSURBVAjXZctBDoAgFAPRIiKKCjj3P6wxGOOHt2w60sdNXqM5AEvsZ7fy2Px4bv7Je8YmMWC1JO30jiSd5FKtkrluiNcGRa90EegAAAAASUVORK5CYII=" alt="" />
);

export default LogoutPointer;
